name: VISUEL II Hizq
favicon: null
layout_spectrum: 0
typography_spectrum: 0.5519713
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9A9891'
    - '#F0AE31'
    - '#EBF0F3'
    - '#A28A4B'
    - '#2E2018'
  brandStrength: 1
  lightness: 0.5625
  saturation: 0.5913978
  rhythmicContrast: 1
purpose: []
