name: VISUEL II Hizq
favicon: null
layout_spectrum: 0.37454628688283265
typography_spectrum: 0.06872162106446922
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6482399571686983
  lightness: 0.2928858946543187
  saturation: 0.9257670140359551
  rhythmicContrast: 0.603613622719422
purpose: []
